demo firefox cert failure

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -1,9 +1,9 @@
 name: Playwright Tests
 on:
   push:
-    branches: [ main, master ]
+    branches: [ main, master, firefox_cert, chrome_cert ]
   pull_request:
-    branches: [ main, master ]
+    branches: [ main, master, firefox_cert, chrome_cert ]
 jobs:
   test:
     timeout-minutes: 60
@@ -19,6 +19,33 @@ jobs:
       run: pnpm exec playwright install --with-deps
     - name: Show env
       run: npx envinfo --preset playwright
+
+    - name: Run `playwright test`, install cert, then run `playwright test` again
+      shell: bash
+      run: |
+        echo "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ demoing that playwright fails with all 3 browsers before cert installed"
+        NODE_EXTRA_CA_CERTS=$(mkcert -CAROOT)/rootCA.pem DEBUG=pw:webserver pnpm exec playwright test || true
+
+        echo "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ installing certs"
+        sudo apt install libnss3-tools
+        curl -L -o mkcert "https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-linux-amd64"
+        chmod +x mkcert
+        sudo mv mkcert /usr/local/bin/mkcert
+        mkcert -install
+        mkdir .cert
+        mkcert -key-file .cert/key.pem -cert-file .cert/cert.pem localhost
+
+        echo "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ build and serve (in background)"
+        pnpm run build
+        pnpm run serve &
+        sleep 10
+
+        echo "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ curl works and recognizes cert"
+        curl -v https://localhost:3000/
+
+        echo "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ chrome and webkit pass, but firefox fails to see cert"
+        NODE_EXTRA_CA_CERTS=$(mkcert -CAROOT)/rootCA.pem DEBUG=pw:webserver pnpm exec playwright test
+
     - name: Run Playwright tests
       run: pnpm exec playwright test
     - uses: actions/upload-artifact@v4
